inherit_from:
  - .rubocop.yml

RSpec/ExampleLength:
  Max: 20

RSpec/ExpectActual:
  Exclude:
    - 'test/missing_formula_spec.rb'

RSpec/MultipleExpectations:
  Max: 5

RSpec/DescribeClass:
  Exclude:
    - 'test/cmd/**'
    - 'test/dev-cmd/**'
